//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationDeVoiture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public Nullable<int> idclient { get; set; }
        public Nullable<int> prix { get; set; }
        public Nullable<System.DateTime> date_debut { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public int idlocation { get; set; }
        public string matricule { get; set; }
    }
}
