//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationDeVoiture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voiture
    {
        public string matricule { get; set; }
        public string marque { get; set; }
        public string modele { get; set; }
        public string disponible { get; set; }
        public int idvoiture { get; set; }
    }
}
